### ISSUE TITLE
Create animation for "Where to Start" section of the home page.

### ISSUE THREAD

**Issue by jlengstorf** [openwhisk/openwhisk.github.io#10]
- [x] Design where to start animation (@yumeforever)
- [x] Add animation to the home page

**Comment by yumeforever** [comment]
Done and good for review. Due the time constrains that was the best I could do :) I was working during some hours to that result. Let me know if something is incorrect. 
@nauerz-ibm @jlengstorf
![animation-test-regular](https://cloud.githubusercontent.com/assets/3612533/20977002/86598286-bca4-11e6-9d0e-e71144c5d42a.gif)
