### ISSUE TITLE
Proposal: Hide Developers, Service Integrators, and Contributors nav items on smaller viewports.

### ISSUE THREAD

**Issue by jlengstorf** [openwhisk/openwhisk.github.io#100]
Since the home page directs people to the various use cases with big ol' buttons, and since [hamburger navs are _awful_ for UX](https://www.nngroup.com/articles/killing-global-navigation-one-trend-avoid/), I think we can buy back some screen real estate on smaller viewports by hiding these nav items.

This would _only_ happen when horizontal space is too limited to display the full nav.

This affects the mobile-friendliness of the site (#36), so we should talk about it sooner rather than later.

Tagging @nauerz-ibm, @krook, @mrutkows, @jthomas, @yumeforever for feedback.

**Comment by jthomas** [comment]
:+1: on this. I'd find it difficult to hit the links on a mobile screen from this header section.
