### ISSUE TITLE
Create illustrations for the Service Integrators page.

### ISSUE THREAD

**Issue by jlengstorf** [openwhisk/openwhisk.github.io#12]
Currently blocked by #28. Once we get the content, we need the following from @yumeforever:

- [x] Illustration for section 1
- [x] Illustration for section 2
- [ ] Illustration for section 3

(We should update these todos with actual feature/section headlines once we have them.)

**Comment by yumeforever** [comment]
My suggestion for the design of this page 
![service developer 2x](https://cloud.githubusercontent.com/assets/3612533/20929134/1ce8f042-bbc9-11e6-8403-c457c1c6c885.png)

**Comment by yumeforever** [comment]
@jlengstorf I don't think there will be a third block for this one. @krook @mrutkows can I use Apache symbol this way?

**Comment by jlengstorf** [comment]
@yumeforever There's a third section now. See https://github.com/openwhisk/openwhisk.github.io/issues/28#issuecomment-265194377 for the copy.
