### ISSUE TITLE
Design Events page.

### ISSUE THREAD

**Issue by jlengstorf** [openwhisk/openwhisk.github.io#13]
This is a list of upcoming events where the OpenWhisk team will be, plus a list of past events.

- [x] Design listing of upcoming and past events (@yumeforever)

For now, we can probably stay pretty close to this general layout (but prettier): https://developer.ibm.com/openwhisk/events/

For later, we can discuss combining this with the updates page that @krook and @mrutkows mentioned.

**Comment by krook** [comment]
Would be nice to automate this in the future. For example, pulling meetup.com events tagged "openwhisk" from their API.

**Comment by jlengstorf** [comment]
@krook I created an issue in the icebox (#46) so we can revisit automating this after the initial launch.

**Comment by yumeforever** [comment]
Done! Sorry @jlengstorf for the slightly change on the Text structure, but it was not pleasing at all :(

![events 2x](https://cloud.githubusercontent.com/assets/3612533/20933752/4f2e9f92-bbd9-11e6-8a0f-2b774f1acf92.png)
