### ISSUE TITLE
Update logos for Partners page.

### ISSUE THREAD

**Issue by jlengstorf** [openwhisk/openwhisk.github.io#14]
- [x] Add Apache logo
- [x] Add SiteSpirit logo

@yumeforever here are the logo files:

- [Adobe_standard_logo_RGB.pdf](https://github.com/openwhisk/openwhisk.github.io/files/631909/Adobe_standard_logo_RGB.pdf)
- [LOGO-SITESPIRIT.ai.zip](https://github.com/openwhisk/openwhisk.github.io/files/631910/LOGO-SITESPIRIT.ai.zip)

**Comment by yumeforever** [comment]
I finished this one and also exported those logos already. 
Please let me know, if those logos are correct. Specially Adobe and Apache, if it is ok to use them like that. From what I found online on their website it looks fine.

exported assets: https://ibm.box.com/s/dtup9jgeqixed7r9hchezmapnx49mpmp

![screen shot 2016-12-08 at 14 26 00](https://cloud.githubusercontent.com/assets/3612533/21011622/66c28392-bd52-11e6-9658-c54f0e292403.png)

**Comment by jlengstorf** [comment]
I think this is fine. I'll finish #35 and close this with a PR.

**Comment by jlengstorf** [comment]
Closed by #113
