### ISSUE TITLE
Bigger blog link

### ISSUE THREAD

**Issue by triceam** [openwhisk/openwhisk.github.io#146]
The link to the blog in Medium is really easy to miss.  Can we make it bigger.  The current link is a tiny "M" that is hard to see.  I think we'll get more traffic by making it more obvious.

**Comment by jlengstorf** [comment]
I think this is a great idea. Looks like @krook already added it to #123, but I'd also like to chime in and encourage any further discussion about this to happen on #123 itself in the interest of keeping everything in one place.
