### ISSUE TITLE
Add Apache branding to OpenWhisk logo in the top nav.

### ISSUE THREAD

**Issue by jlengstorf** [openwhisk/openwhisk.github.io#15]
- [x] Add "Apache" into the OpenWhisk logo in the top nav

@yumeforever: see the [Cordova](https://cordova.apache.org/) site for inspiration on this.

**Comment by krook** [comment]
Should also be in the text above the call to action button.

**Comment by yumeforever** [comment]
If I understood well, that's how Cordova does.
apart of text, this is the only place where the logo itself appear.
If everything is ok, I think that's done. 

![screen shot 2016-12-07 at 11 09 13](https://cloud.githubusercontent.com/assets/3612533/20963437/9cc7e1ac-bc6d-11e6-9a27-f7e41cc616e0.png)

**Comment by jlengstorf** [comment]
@yumeforever Looks good to me. Adding to my dev queue.
