### ISSUE TITLE
Re-brand partners section

### ISSUE THREAD

**Issue by wikier** [openwhisk/openwhisk.github.io#158]
As started to discuss with PR #157, we need to re-brand the current partners section to have something more community oriented.

**Comment by krook** [comment]
@wikier Here is a proposal we can discuss on the dev list:

1. Change "partners" to "supporters"
2. Agree that nobody gets listed by default, and create guidance on how to get listed if desired.
3. Ask the existing listed partners if they still want to be included. If so, ask for a statement describing their contribution to the project.

**Comment by wikier** [comment]
Sound reasonable, @krook.

I still don't like "supporters" at all, but unless some comes up with a better idea, I guess we could go with that for now.
