### ISSUE TITLE
Social Icons at the header and footer way too small to see

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk.github.io#168]
Make them larger
![image](https://cloud.githubusercontent.com/assets/1094878/22525107/f1997db0-e893-11e6-92b4-fbf5ca7a905c.png)

**Comment by krook** [comment]
Related to #146 and #123

**Comment by csantanapr** [comment]
@krook you making a PR for the CSS change the size?

**Comment by krook** [comment]
@csantanapr I had looked into how to do it a few weeks ago (https://github.com/openwhisk/openwhisk.github.io/issues/123#issuecomment-271999943). I didn't see @jlengstorf's reply to my question though. I will give it a shot now that I have the info.
