### ISSUE TITLE
Address web site requirements for Graduation from the Apache Incubator

### ISSUE THREAD

**Issue by krook** [openwhisk/openwhisk.github.io#170]
The requirements and guidelines are listed here: http://incubator.apache.org/guides/sites.html

> Podlings are, by definition, not yet fully accepted as part of the Apache Software Foundation. Therefore, they are subject to additional constraints on their websites. These policies MUST be adhered to before Graduation is considered unless prior approval is obtained from the Incubator PMC.

As we address these requirements and guidelines, we should also ensure that they help us effectively achieve our community building goals as described in Issue #123.

We should track progress in a Markdown checklist in a file such as `APACHE_WEBSITE_REQUIREMENTS.md`.

**Comment by mrutkows** [comment]
or on our CWIKI: https://cwiki.apache.org/confluence/display/OPENWHISK/OpenWhisk+Project+Wiki

which would be cleaner and avoid adding a temp. file in the repo. itself.  Your call.

**Comment by krook** [comment]
@mrutkows That is a better idea as the checklist will be read/edited several times. Can you please create a wiki page based on the checklist I put in the PR? I'll cancel the PR after.

**Comment by krook** [comment]
New wiki page is at: https://cwiki.apache.org/confluence/display/OPENWHISK/Compliance+Checklist+for+OpenWhisk.org+website
