### ISSUE TITLE
bin/develop fails on mac osx

### ISSUE THREAD

**Issue by mrutkows** [openwhisk/openwhisk.github.io#172]
1) installed clean node/npm latest build for mac osx (Sierra 10.12.3).  
node -v : v6.9.5
npm -v : 3.10.10

2) executed bin/develop and resulted in an error.  

See attached .log for details
<img width="885" alt="screen shot 2017-02-02 at 10 48 45 am" src="https://cloud.githubusercontent.com/assets/7816715/22559112/bf323a5e-e935-11e6-945d-46171c4b0e7a.png">

**Comment by mrutkows** [comment]
.log is not supported attachment type.  I am pasting the contents here:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'dev' ]
2 info using npm@3.10.10
3 info using node@v6.9.5
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle openwhisk.org@0.1.0~predev: openwhisk.org@0.1.0
6 silly lifecycle openwhisk.org@0.1.0~predev: no script for predev, continuing
7 info lifecycle openwhisk.org@0.1.0~dev: openwhisk.org@0.1.0
8 verbose lifecycle openwhisk.org@0.1.0~dev: unsafe-perm in lifecycle true
9 verbose lifecycle openwhisk.org@0.1.0~dev: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/Matt/whisk/openwhisk.github.io/node_modules/.bin:/Library/Frameworks/Python.framework/Versions/3.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin:/usr/local/go/bin
10 verbose lifecycle openwhisk.org@0.1.0~dev: CWD: /Users/Matt/whisk/openwhisk.github.io
11 silly lifecycle openwhisk.org@0.1.0~dev: Args: [ '-c', 'run-p dev:* --silent' ]
12 silly lifecycle openwhisk.org@0.1.0~dev: Returned: code: 1  signal: null
13 info lifecycle openwhisk.org@0.1.0~dev: Failed to exec dev script
14 verbose stack Error: openwhisk.org@0.1.0 dev: `run-p dev:* --silent`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid openwhisk.org@0.1.0
16 verbose cwd /Users/Matt/whisk/openwhisk.github.io
17 error Darwin 16.4.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
19 error node v6.9.5
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error openwhisk.org@0.1.0 dev: `run-p dev:* --silent`
22 error Exit status 1
23 error Failed at the openwhisk.org@0.1.0 dev script 'run-p dev:* --silent'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the openwhisk.org package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     run-p dev:* --silent
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs openwhisk.org
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls openwhisk.org
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by mrutkows** [comment]
npm -v Darwin :
3.10.10

**Comment by mrutkows** [comment]
failure in package.json for "dev" target on line [8]:

[7]     "build:js": "NODE_ENV=production rollup -c",
[8]     "dev": "run-p dev:* --silent",
[9]     "dev:jekyll": "bundle exec jekyll serve",
[10]    "dev:js": "rollup -c --watch",

are there other pre-reqs that need to be installed?

**Comment by krook** [comment]
If it helps debugging whether it's specific to your environment... It works for me and I have: 
OSX El Capitan (10.11.6)
node -v: v6.9.4
npm -v 3.10.10

**Comment by mrutkows** [comment]
My fear is that this is a Sierra issue...  I did a complete "wipe" (even though it was a fresh install) and used a suggested "wipe" script as well and same issue upon re-install.

**Comment by krook** [comment]
@mrutkows What was the eventual resolution to this? Maybe @jlengstorf and @csantanapr ran into the same issue? We should also document that bin/develop needs to be restarted to pick up CSS changes. It's good about regular content changes.

**Comment by jlengstorf** [comment]
It actually looks like the error — at least for @mrutkows — is that Ruby is missing.

If you've got Homebrew installed, you can use:

    brew install ruby

Since this site is built on Jekyll, which is a Ruby app, it's required for local dev.

**Comment by mrutkows** [comment]
@jlengstorf I got it working and am updating the README

**Comment by mrutkows** [comment]
Updated readme on PR:
https://github.com/openwhisk/openwhisk.github.io/pull/174
