### ISSUE TITLE
Add my upcoming talks on OW

### ISSUE THREAD

**Issue by cfjedimaster** [openwhisk/openwhisk.github.io#181]
I'm speaking at ForwardJS (https://forwardjs.com/) on OpenWhisk. The talk is "Serverless or Bust". Unfortunately there is no direct link to the session yet.

I'm also speaking on OW at "Into the Box" (https://www.intothebox.org/). Unfortunately, no direct link either.

**Comment by krook** [comment]
This can be closed @cfjedimaster. Both events are already on the events page.
