### ISSUE TITLE
Include Dashdb (DB2) drivers in the node.js (and other) runtimes

### ISSUE THREAD

**Issue by mpuittinen** [openwhisk/openwhisk.github.io#184]
Developing a customer solution on Bluemix that need to access a Dashdb database. Our current workaround is to create a docker image with the drivers (not sure whether license allows that), but the cold start time is absolutely horrible (20secs).

Please include the DB2 driver binaries (and Node modules) in the standard Node.js Openwhisk runtime.

**Comment by markusthoemmes** [comment]
@mpuittinen thanks for reaching out. You probably want to open this issue in the core repository at https://github.com/openwhisk/openwhisk/issues

**Comment by mpuittinen** [comment]
Posted that to the openwhisk registry https://github.com/openwhisk/openwhisk/issues/1932
