### ISSUE TITLE
Choose pull quotes for Service Integrators page (2).

### ISSUE THREAD

**Issue by jlengstorf** [openwhisk/openwhisk.github.io#23]
- [ ] Choose 10–25 words of praise or review from two reviews
- [ ] Provide citation (name, source link, publication)

If possible, it would be great to include an avatar or publication logo. See #21 for discussion about legality of doing so.

**Comment by nauerz-ibm** [comment]
Would pick this one (but make sure to not use this at other places, too):

Altorors, Andrei Yurkevich, CTO
What excites me most is its open-source nature, which creates a foundation for a broad ecosystem of contributing parties.

Nepente, André Poleza, Co-Founder (willing to talk to the press: YES)
Their modular and effective ecosystem twisted our minds
