### ISSUE TITLE
Choose pull quotes for Contributors page (2).

### ISSUE THREAD

**Issue by jlengstorf** [openwhisk/openwhisk.github.io#24]
- [ ] Choose 10–25 words of praise or review from two reviews
- [ ] Provide citation (name, source link, publication)

If possible, it would be great to include an avatar or publication logo. See #21 for discussion about legality of doing so.

**Comment by nauerz-ibm** [comment]
@jlengstorf 

Here is the first one, still searching for a second one (cannot promise I will find a proper one in time):

Altorors, Andrei Yurkevich, CTO (willing to talk to the press: UNCLEAR)
“In the Industrial Internet era, it is important to work with solutions that are flexible, easily maintained, and process data in real time,” said Andrei Yurkevich, CTO at Altoros. “In this endeavor, we are very proud to be one of the early users of OpenWhisk. This technology enables rapid creation of serverless, trigger-based systems for a variety of customers we are working on—in finance, healthcare, manufacturing, transportation, logistics, etc.”

Altorors, Andrei Yurkevich, CTO
OpenWhisk is really unique in the way it can be consumed on a per-use basis on IBM Cloud, as well as in a private datacenter. What excites me most is its open-source nature, which creates a foundation for a broad ecosystem of contributing parties. Having strong expertise in creating microservice-based architectures on IBM Bluemix and open-source Cloud Foundry, we at Altoros are glad to see OpenWhisk going to production and would be happy to share our experience with the adopters of technology.

**Comment by yumeforever** [comment]
Updated with design at #11

**Comment by nauerz-ibm** [comment]
Here some statements from Twitter (wouldn't use the tweeters name):

> Very impressed by the openess of IBM OpenWhisk #serverlessconf

> Apparently @openwhisk is the only fully open source #serverless technology, can run in-house too, its on git at

> So far I find #OpenWisk the real highlight of this #serverlessconf London, I’m totally amazed by the work done so far by the dev team! kudos

> @trieloff says #OpenWhisk is going to become an #Apache project. That's exciting! #serverlessconf

**Comment by nauerz-ibm** [comment]
If the tweets don't work pick a 2nd statement from here:
http://thenewstack.io/exploring-pros-cons-serverless-computing-ibm-openwhisk/

Let me know if all that does not work.

**Comment by yumeforever** [comment]
@nauerz-ibm Isn't this too IBM driven? :/

**Comment by nauerz-ibm** [comment]
Ah, that is true... better use the tweets :)

**Comment by yumeforever** [comment]
@nauerz-ibm can we use the user's name? Or just the claims?

**Comment by yumeforever** [comment]
@jlengstorf Is it possible to do something like that? @nauerz-ibm for the contributor page 
![screen shot 2016-12-06 at 15 16 51](https://cloud.githubusercontent.com/assets/3612533/20928637/14a97a98-bbc7-11e6-99bc-0c28c9c8a3d4.png)
