### ISSUE TITLE
Edit content for Service Integrators panel of the home page.

### ISSUE THREAD

**Issue by jlengstorf** [openwhisk/openwhisk.github.io#25]
From @nauerz-ibm:

> How about this (pls rephrase a bit, 1st sentence is too long):
> 
> OpenWhisk relies on an open ecosystem of services provided by different vendors and falling into 
> different domains like analytics, cognitive, data, IoT, and mobile. These services represent 
> powerful building blocks - fostering re-use and avoiding reinventing the wheel, hence accelerating 
> overall development - providing totally different capabilities developers can make use of to build 
> compelling serverless event-driven solutions.
> 
> Evem better, OpenWhisk provides an open event provider interface that allows it everybody to let 
> his own service become part of OpenWhisk’s ecosystem to drive traffic & usage.

**Comment by jlengstorf** [comment]
If the goal of this section is to convince other companies to create packages for their service, I think we should focus more on how _they_ benefit by doing so.

How about this, @nauerz-ibm @krook @mrutkows?

> ## Add Your Service to Apache OpenWhisk
> 
> Apache OpenWhisk makes it simple for thousands of developers to integrate with your service. Make it easy for developers to perform actions when something happens in your service, or to send data into your service when things happen somewhere else.
> 
> Become part of a thriving, open-source ecosystem: get your service into the hands of more developers, and make it easier than ever to integrate with your services.

**Comment by yumeforever** [comment]
My design suggestion for this one #12

**Comment by nauerz-ibm** [comment]
@jlengstorf Love the suggestion you made above... thanks for having rephrased my original input!

**Comment by nauerz-ibm** [comment]
@yumeforever Love the design... go for it...

**Comment by yumeforever** [comment]
@jlengstorf I think we should repeat the call to action in the bottom I just created for Contributors for those pages (Developer, Integrator and Contributor). What do you think?
If we already know what are those. 
![screen shot 2016-12-06 at 15 35 52](https://cloud.githubusercontent.com/assets/3612533/20929290/c129409e-bbc9-11e6-92ab-b1b7c70160e0.png)

**Comment by krook** [comment]
@jlengstorf I agree this copy for the homepage looks good. Let's go with it.
