### ISSUE TITLE
Write lede + 3 feature overview sections for Service Integrator page.

### ISSUE THREAD

**Issue by jlengstorf** [openwhisk/openwhisk.github.io#28]

**Comment by krook** [comment]
@mrutkows is definitely going to need to be involved with this one.

**Comment by jlengstorf** [comment]
@mrutkows I took a swing at a synopsis in [this comment](https://github.com/openwhisk/openwhisk.github.io/issues/25#issuecomment-264993317). If you're editing this page, it's probably worth checking that at the same time.

**Comment by jlengstorf** [comment]
Per Slack discussion. Can we get edits and/or an approval on this, @mrutkows?

> ## Build a Community of Developers around your Service
> Apache OpenWhisk provides an open framework for serverless application developers to integrate event sources and data services from anywhere on the Internet. By integrating your services as an OpenWhisk package, you'll gain access to a community of developers building the next generation of cloud native applications.
> 
> ## Unlock unlimited third-party integrations.
> Staying up-to-date with third-party integrations can be expensive and time-consuming. By adding your service as an Apache OpenWhisk package, developers can integrate your service with _anything_, with no time or investment from your team. Simply create a package for your service and unleash the creativity of your users!
> 
> ## Join a Growing Ecosystem of Service Integrators
> When you build a package for Apache OpenWhisk, you join an emerging community of package integrations. Does your package work with GitHub? Or Slack? Or can it drive IBM Bluemix Watson cognitive functions? Find out more about the existing packages and their features that OpenWhisk developers are using today.

**Comment by yumeforever** [comment]
Assuming we go with this idea, I was creating this visuals.
![service developer 2x](https://cloud.githubusercontent.com/assets/3612533/20935464/206ad602-bbdf-11e6-8871-0a913fa8136a.png)
