### ISSUE TITLE
Write lede + 3 feature overview sections for Contributors page.

### ISSUE THREAD

**Issue by jlengstorf** [openwhisk/openwhisk.github.io#29]
Initial ideas from @nauerz-ibm:

> Serverless computing is already showing its potential to become a game-changer for cloud-native application development.
> 
> Are you interested to become part of a strong community & work on a bleeding edge technology?
> 
> It does not matter whether you are an application developer, a service integrator or someone keen to help us working on the core engine itself. We welcome everybody willing to help…
> 
> If you are an application developer show us what you have already build or what you plan to build with OpenWhisk and we will promote your solution within our community so you can get feedback for free to make your solution even better. We even welcome you to share your rules, actions, and triggers and – in return – benefit from others doing the same preventing people from reinventing the wheel.
> 
> If you are a service integrator you should definitely consider enabling your service for OpenWhisk to let it become part of a growing ecosystem. Being part of our ecosystem will make your service more attractive to other developers building OpenWhisk-based serverless & event-driven solutions. This will drive traffic & usage of your service.
> 
> If you are an open-source contributor working with us is your chance to learn something new & broaden your skillset. Help us to drive & accelerate the development of this technology. Help us proposing or even adding more cool features. Start participating today - in something that itself has been built upon open technologies like Scala, Docker, Consul, Kafka…
> 
> In any case: We are looking forward to hear about your ideas and benefit from your contributions. Join the community and become part of the OpenWhisk game.

**Comment by jlengstorf** [comment]
I'll take a crack at editing this into a format that matches the other pages. Should have it in today.

**Comment by jlengstorf** [comment]
@mrutkows @krook @nauerz-ibm — here's a stab at the main headline, main CTA, and subheadings for the Contributors page (placeholder image attached for layout reference):

> # Play a critical part in building game-changing cloud technology.
> 
> Button: [Learn About Contributing](#link?)
> 
> ## Share your great ideas with the community.
> 
> Have you built something great using Apache OpenWhisk? Share your rules, actions, and triggers with the community! We'll help to promote your work to the community, and you'll help to grow the community library of ready-to-use code available to other deveopers. Everybody wins!
> 
> ## Get thousands of developers using your service.
> 
> Make your product or service even more attractive to developers by becoming part of Apache OpenWhisk's growing ecosystem. Create a package to allow developers to use your service with Apache OpenWhisk, open it to the community, and join the serverless revolution!
> 
> ## Build new skills. Build a community.
> 
> Pad your resume by contributing to bleeding-edge, serverless technology. Become part of a growing community of open-source developers working to improve Apache OpenWhisk. Propose a feature, submit a pull request, or create a tutorial — help build a movement!

I think I'd like to see an individual CTA for each subsection. I know that breaks the pattern established on the Developers/Service Integrators pages, but I also think there are three very different paths on this page, and there's not really a single next action that makes sense for all three.

Thoughts?

![contributors](https://cloud.githubusercontent.com/assets/163561/20905203/de3b000a-bb10-11e6-924c-fc9c14ce05fe.png)

**Comment by yumeforever** [comment]
I agree with @jlengstorf on the CTA for each section, but in my view from here on what they could/would like to do is to know more about the code and try OpenWhisk.
I don't know how it works with Open Source project, how they can actually contribute, what are the steps to start.. but something related to that. What do you guys think?

**Comment by yumeforever** [comment]
Ps: Does **"Get thousands of developers using your service."** really apply to Open Source Contributors? @nauerz-ibm Isn't this just about the Service Integrators?

**Comment by jlengstorf** [comment]
@yumeforever I think the Contributors page is a little different from the others; a Contributor can be a Developer or a Service Integrator. So the copy speaks to the benefits for both groups.

The copy above shows benefits to these groups in this order:

1. Developers who build their own tools and want people to use them. (CTA => how to publish an action?)
2. Apps and services who want to use OpenWhisk as a platform. (CTA => how to create a package?)
3. Developers who are interested in working on OpenWhisk itself. (CTA => see open issues on GitHub?)

Feel free to jump in and correct me if I'm misunderstanding. 😄

**Comment by yumeforever** [comment]
Oh.. I just saw this reply. I had a shot on this page right now at #11 .. I guess I should design this section 2 then, about the Apps and services who want to use OpenWhisk as a platform.

**Comment by nauerz-ibm** [comment]
@jlengstorf is right when saying " I think the Contributors page is a little different from the others; a Contributor can be a Developer or a Service Integrator. So the copy speaks to the benefits for both groups."

Imho we should point out values like:
- Be part of a strong community
- Work on somehting bleeding edge
- Learn something new (have fun)
- Broaden your skillset (and improve your employability)
- Show others what you have build and get feedback
- Share what you have build and allow others to reuse
- Integrate your services
- Add new features to the core engine itself

@krook @mrutkows What do you guys think are the key points we should make here?
I want to encourage others to participate...

**Comment by jlengstorf** [comment]
@nauerz-ibm I tried to call out to those benefits in the copy above, but space is limiting and I was worried about reducing the copy to a meaningless ball of buzzwords. If you want to take a crack at editing any of the sections, I'm game.

In the meantime, I'm going to put the copy in place as-is so we can soft launch.
