### ISSUE TITLE
Edit all content to include Apache branding when mentioning OpenWhisk.

### ISSUE THREAD

**Issue by jlengstorf** [openwhisk/openwhisk.github.io#30]
Any instance of "OpenWhisk" in the copy should be updated to "Apache OpenWhisk".

**Comment by fmeschbe** [comment]
For reference here are some guidelines as discussed:

- http://www.apache.org/foundation/marks/pmcs.html - General website branding guidelines
- http://incubator.apache.org/guides/branding.html - specific extensions for incubating projects like OpenWhisk

Please note the specific requirement of adding the incubator logo onto the site. As an example see the footer of the Hawk site: http://hawq.incubator.apache.org/
