### ISSUE TITLE
Build Partners page.

### ISSUE THREAD

**Issue by jlengstorf** [openwhisk/openwhisk.github.io#35]
- [ ] Update main heading and lede (@nauerz-ibm)
- [x] Create illustration for header (@yumeforever)
- [ ] Code it all up (@jlengstorf)

<img width="653" alt="screencap-by-jlengstorf 4" src="https://cloud.githubusercontent.com/assets/163561/20897389/20f84f04-baf0-11e6-8522-017c124d39c3.png">

**Comment by jlengstorf** [comment]
From @nauerz-ibm:

> Our partners are companies or individuals interested in serverless computing in general and OpenWhisk in particular. Some of them use OpenWhisk to develop and impressive serverless & event-driven solutions, others enable their own services to let them become part of the ever-growing OpenWhisk ecosystem to increase their service's traffic & usage, and others simply work with us to help us to drive & accelerate the development of this bleeding edge technology.
> 
> If you are interested in partnering with us, too do not hesitate to get in touch and discuss...

**Comment by krook** [comment]
I think we need to align this with not only the Service Integrators page/persona, but we may want to point them to a mailing list, or specific OpenWhisk vendor pages. We should look at Apache precedents for this sort of thing.

**Comment by nauerz-ibm** [comment]
Agree to @krook 
Despite that I forwarded the logos of Apache and others via mail to make sure they get included, too.

After GA we should add some textual description for each partner - instead of having logos only - to describe what exactly they are doing with OpenWhisk/jointly with us. But imho not that urgent.

**Comment by jlengstorf** [comment]
@nauerz-ibm — edits here:

> # Meet Our Partners
> 
> Our partners are working to develop new serverless and event-driven solutions, create packages to add new services to the ever-growing Apache OpenWhisk ecosystem, and advance the development of this game-changing technology.
> 
> If you're interested in partnering with us, [get in touch](#link?) or [join the mailing list](#link?).

Is there a process for becoming a partner? Asking them to contact us is pretty open-ended, which will probably lead to inaction in a lot of cases. If we can figure out a simple way — say a form or something — that allows interested companies to check a couple boxes to show interest rather than composing a free-form email, we'll probably see better conversion here.

**Comment by yumeforever** [comment]
If everyone agrees:
![screen shot 2016-12-06 at 16 25 56](https://cloud.githubusercontent.com/assets/3612533/20931230/ba25dc2e-bbd0-11e6-87c3-10e3c1782499.png)

**Comment by jlengstorf** [comment]
@yumeforever We have to make the Adobe logo fit here — see #14 — which is vertical. It's going to be 5 total logos here. Would you be willing to put this together with the final logos so we can see it?

My gut says we need to drop the blue background from the logos, and maybe center them (3 in the first row, 2 in the second), but I'll trust your eye.
