### ISSUE TITLE
Create content for the Imprint page.

### ISSUE THREAD

**Issue by jlengstorf** [openwhisk/openwhisk.github.io#45]
There is an "Imprint" page in the footer nav at the moment.

- [ ] Confirm whether or not this page is legally required.
- [ ] Write content for the page.

**Comment by nauerz-ibm** [comment]
I am pretty sure it is required for legal reasons.
I have dropped Ed, our IP guy, a mail to confirm and to help us with assembling the proper content.
I have cc'd you.

**Comment by nauerz-ibm** [comment]
Based on @krook input we do not need an imprint at all, hence closing this issue.
