### ISSUE TITLE
Should find a way to integrate material as needed from Awesome OpenWhisk

### ISSUE THREAD

**Issue by krook** [openwhisk/openwhisk.github.io#48]
This repo has lots of good stuff that each of the personas might like as getting started material: https://github.com/openwhisk/awesome-openwhisk

**Comment by jlengstorf** [comment]
I added a link in the FAQ (see #75).

**Comment by jlengstorf** [comment]
There's an issue discussing how to incorporate content like this (#123). Let's focus discussion there to keep it in one place for now.

**Comment by jlengstorf** [comment]
@mrutkows just opened an issue to actually _absorb_ this repo, so I'm closing this one in favor of #135.
