### ISSUE TITLE
Review FAQ Links

### ISSUE THREAD

**Issue by yumeforever** [openwhisk/openwhisk.github.io#52]
We need to review the FAQ Questions and Answers. Bluemix is everywhere and we might want to change.

**Comment by krook** [comment]
Should work with Bluemix offering management to ensure those specific FAQs are now addressed elsewhere on ibm.com.

**Comment by krook** [comment]
Here's my first take on what should stay and what should go:

- What is event-driven programming and serverless computing? **(link to openwhisk.org serverless page)**
- What problems does OpenWhisk solve? What can you do with OpenWhisk?
- How is it open?
- Which offerings are available?
- ~~Why wouldn’t I just get the corresponding open-source code OpenWhisk is build on and run it myself? What added value does IBM Bluemix provide?~~
- ~~When will OpenWhisk for IBM Bluemix be beta/GA?~~
- ~~Is OpenWhisk for IBM Bluemix able to scale and performant to support enterprise apps?~~
- ~~Which support is provided with OpenWhisk particularly for mobile back-ends and front-ends?~~
- ~~Which IBM Bluemix services is OpenWhisk best paired with?~~
- Can I enable my own services for OpenWhisk?
- Which programming languages/runtimes does OpenWhisk support?
- When should I use OpenWhisk versus VMs, Containers, or Cloud Foundry apps? **(we have a Bluemix specific page here. May have to reword)**
- ~~What does OpenWhisk cost?~~
- Where can I go to learn more? **(should the blog and media pages link elsewhere)**
- Are there videos, demos, or sample code that I can have a look at? **(revisit links)**
- Who are the OpenWhisk open-source partners? **(should link to partners page)**
- How do I get involved? **(link to contributors page)**
- Need another question answered? **(link to all of the social channels)**
