### ISSUE TITLE
Send email about the new openwhisk.org and how to contribute to dev@openwhisk.incubator.apache.org 

### ISSUE THREAD

**Issue by krook** [openwhisk/openwhisk.github.io#59]
This should be done after launch and once we've moved to Apache web site management process.

**Comment by jlengstorf** [comment]
@krook @mrutkows So, I don't know that I _can_ email the dev list. I tried to respond to a message earlier, and since IBM's mail is only `text/html`, the dev list rejected it. I can't find a setting to change to `text/plain`, so... I don't know how to send a message.

**Comment by krook** [comment]
I posted a note yesterday. Conversation started [here](http://mail-archives.apache.org/mod_mbox/incubator-openwhisk-dev/201702.mbox/%3COF14BEC4FF.FCCCC022-ON852580BA.00702C1F-852580BA.0071AA68%40notes.na.collabserv.com%3E).

**Comment by csantanapr** [comment]
@jlengstorf that's weird, since there are other people sending emails @us.ibm.com  like @krook and @markusthoemmes 
Do you use verse or lotus notes native client?

let's chat on Slack to see if we can get you fix to be able to post to the dev list

**Comment by dubeejw** [comment]
@jlengstorf, @csantanapr, I had to use Notes to send an email to the dev list instead of Verse.

**Comment by csantanapr** [comment]
@dubeejw oh my, we need to find a better way. I use gmail :-)

**Comment by mrutkows** [comment]
@dubeejw is there a way to adjust the mail format (i.e., restrict to "plain text"), most email apps. should allow this somewhere...  I suspect that HTML (only) header/format is being sent and that there may be a perceived HTML error (and not plain text version to fall back to).  I believe Notes always sends both a plain text and HTML version.

**Comment by mrutkows** [comment]
oh, and as a second test...   assure that you are not attaching images to your emails (e.g., in a signature) even if its HTML format can cause issues depending on image format.
