### ISSUE TITLE
Update Contributors section on home page.

### ISSUE THREAD

**Issue by jlengstorf** [openwhisk/openwhisk.github.io#6]
Needs illustration from @yumeforever.

<img width="778" alt="144b29e2-b7cc-11e6-98b8-da3c4e825652" src="https://cloud.githubusercontent.com/assets/163561/20894607/1de3a518-bae4-11e6-9819-398ff6461e91.png">

**Comment by krook** [comment]
If we keep that title, it should read "Be part of a vibrant open source community!"

**Comment by yumeforever** [comment]
Done!
Just please revise the copy, I come up with this to summarize the main points about Open Source Contributor.  Full page (missing one section) at #11 
![screen shot 2016-12-06 at 15 53 58](https://cloud.githubusercontent.com/assets/3612533/20930015/4b0e441a-bbcc-11e6-8437-c060599aee89.png)

**Comment by jlengstorf** [comment]
@nauerz-ibm for copy:

> ### Join a vibrant open-source community!
> Play a critical part in building game-changing cloud technology. Share your actions and rules with the community, add your service to the Apache OpenWhisk ecosystem, or join the development effort to make Apache OpenWhisk even better.

If this is cool (or after you've edited), assign this issue back to me and I'll implement the design/copy.
