### ISSUE TITLE
Flesh out the README / Jekyll preview instructions if needed

### ISSUE THREAD

**Issue by krook** [openwhisk/openwhisk.github.io#61]
May need to enhance the steps with how to configure a local Ruby environment and check out the right branch, be it `feature/new-site` now or `ghpages` after launch.

For example, these may be needed:
`git checkout feature/new-site`
`gem install jekyll`

**Comment by jlengstorf** [comment]
The `feature/new-site` part won't be relevant once we merge to master, but I'll update the Jekyll thing.
