### ISSUE TITLE
Reconfigure nameserver

### ISSUE THREAD

**Issue by nauerz-ibm** [openwhisk/openwhisk.github.io#62]
Please inform @nauerz-ibm to reconfigure the nameserver so openwhisk.com/net/org points to our new website once it is ready.

**Comment by jlengstorf** [comment]
If it's not a problem, let's just do it now. https://openwhisk.github.io/ is already live, and the .org address currently redirects to GitHub.

This would be one less thing to worry about when we go live, and nothing breaks if the github.io site is loaded for a couple days, right?

**Comment by krook** [comment]
We agreed on the playback to do this sooner rather than later for several key reasons:

- It allows us to post to the Apache OpenWhisk dev mailing list for feedback earlier
- It affords us time to approve analytics tracking concerns
- It allows us to serve the design via GitHub pages immediately

**Comment by nauerz-ibm** [comment]
Done.
