### ISSUE TITLE
Promote website via social media (e.g. Twitter)

### ISSUE THREAD

**Issue by nauerz-ibm** [openwhisk/openwhisk.github.io#63]
Please inform the general public once our new website is available via social media (e.g. Twitter).

**Comment by jlengstorf** [comment]
@krook Should we make the announcement?

We could also encourage people to get on the dev mailing list and check out our open issues to get involved. I'm working on an email for the dev list (#59) that will do that same.

**Comment by windowsok** [comment]
It is the   information I am looking for. I'm learning more about this. Hope you bring   more things related to it. Thank you very much!
[abcya](http://abcdeya.com)
