### ISSUE TITLE
Choose analytics tools.

### ISSUE THREAD

**Issue by jlengstorf** [openwhisk/openwhisk.github.io#65]
- Do we need analytics for the site?
- If yes:
  - what are we tracking (e.g. pageviews, video plays, scrolling, etc.)
  - which service(s) are we using?
  - who will set up these accounts?
  - who will monitor these?

**Comment by krook** [comment]
@jlengstorf Damn. You beat me to this. I was looking at the Cordova source earlier today, they use Google Analytics. We can raise on today's playback.

**Comment by krook** [comment]
Until we move to the new Apache hostname, we'll use this Google Analytics information. The account will be transferred at a later time.

```html
<script>
 (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
 (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
 m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
 })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

 ga('create', 'UA-88941444-1', 'auto');
 ga('send', 'pageview');

</script>
```

@jlengstorf Can you please add this to the footer?
