### ISSUE TITLE
Add illustration for "share your service" section of Contributors page.

### ISSUE THREAD

**Issue by jlengstorf** [openwhisk/openwhisk.github.io#78]
- [x] Create illustration (@yumeforever)
- [ ] Update the code (@jlengstorf)

**Comment by yumeforever** [comment]
Done! :) SVG on Share-your-service.svg https://ibm.box.com/s/hbmelj1zovhj3pahrbq882a1wfiu6ehm

<img width="913" alt="screen shot 2016-12-12 at 15 44 39" src="https://cloud.githubusercontent.com/assets/3612533/21103251/ea3add50-c081-11e6-978b-f29238326cc3.png">
