### ISSUE TITLE
Review font licensing to determine whether we can use

### ISSUE THREAD

**Issue by krook** [openwhisk/openwhisk.github.io#80]
Question from @fmeschbe: What is the license situation for the fonts ? Do we have a license to use them on our site ?

**Comment by jlengstorf** [comment]
Current fonts are:

- [Lato](https://fonts.google.com/specimen/Lato), which is under the [Open Font License](http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL_web) — I'm not a lawyer, but I'm _pretty_ sure that's super permissive as licenses go.
- Helvetica Neue for IBM, which we probably ought to drop in favor of standard sans-serif. I doubt anyone but @yumeforever and I will notice, and it avoids a licensing headache _and_ speeds up the site load time. I created #83 to track it.

If everyone's cool with these, please close this issue.

**Comment by fmeschbe** [comment]
Thanks @jlengstorf  and @krook. This sounds good to me and we are green here.
I agree that this can be resolved.

**Comment by yumeforever** [comment]
@jlengstorf Nailed it here https://github.com/openwhisk/openwhisk.github.io/issues/83

**Comment by jlengstorf** [comment]
Thanks, @fmeschbe and @yumeforever! Closing this.
