### ISSUE TITLE
Confirm original HTML/CSS and/or whether boilerplate is properly reused

### ISSUE THREAD

**Issue by krook** [openwhisk/openwhisk.github.io#81]
Question from @fmeschbe: Other pieces like CSS and HTML source are probably built specifically for the site and thus ok as well.

**Comment by jlengstorf** [comment]
I'm not sure what "boilerplate is properly reused" means — is there something I was supposed to build on?

The site's tech stack is:

- [Jekyll](http://jekyllrb.com/) for static site generation with GitHub Pages (MIT license)
- HTML and CSS are from scratch — no frameworks or boilerplates
- All tools for the build pipeline are MIT licensed

**Comment by fmeschbe** [comment]
Thanks @krook  and @jlengstorf.

* The tool chain is less of an importance as long as we have the right to use it. So this is green.
* The HTML and CSS being from scratch means we are green here as well.

Therefore, I think we properly did the diligence on this topic and can resolve this issue.

**Comment by jlengstorf** [comment]
Great news, @fmeschbe! Closing this.
