### ISSUE TITLE
Consider narrower content display area for text-heavy pages.

### ISSUE THREAD

**Issue by jlengstorf** [openwhisk/openwhisk.github.io#92]
I'd like to get another designer's eye on it, but on text-heavy pages I think it might be a good idea to narrow the content column (see attached screenshot). This makes it a little easier to read the copy, and looks a little tighter, I think.

![serverless](https://cloud.githubusercontent.com/assets/163561/20993012/be2fde56-bcb5-11e6-8bab-80254f55320d.png)

I've got a branch ready to send in for a PR if we agree on this.

**Comment by yumeforever** [comment]
I am down to this 🙌 if you expand the top and bottom margins for this quote by double. 
I am really stuck with this illustration though.

**Comment by jlengstorf** [comment]
@yumeforever How's this? 

<img width="1024" alt="screencap-by-jlengstorf 11" src="https://cloud.githubusercontent.com/assets/163561/21013831/739ba6a8-bd29-11e6-82ff-735fc01dc4bb.png">

I'll take a look at the articles from @krook and see if I see anything that might work in the style you've been using on the site.

**Comment by jlengstorf** [comment]
So, what I see as the biggest benefit offered by serverless is the time and effort saved by using it.

In @krook's [article](https://developer.ibm.com/opentech/2016/09/06/what-makes-serverless-attractive/), he talks about "12 Factor Apps", and shows how a serverless approach handles 8 of 12 factors out of the box — which means a developer using serverless has 75% fewer things to worry about when writing good code.

That's _huge_. (Also, @krook: I feel like we should probably mention that in the "what is serverless" page.)

So what about and illustration demonstrating the amount of work required, and showing how much of that work is handled by OpenWhisk?

I see a couple ways to do it:

### 1. A bar graph comparing "traditional" to "serverless"

For example:

```
     |
WORK |  +--+
 TO  |  |XX|                        +--+
 BE  |  |XX|                        |XX|
DONE |  |XX|                 +--+   |XX|
     |  |XX|                 |XX|   |XX|
     +-------------------------------------
        You    Robots    |   You   Robots
         Traditional     |    Serverless
         
                 WHO DOES THE WORK
```

### A comparison showing the actual factors.

For example:

```
TRADITIONAL:  Codebase => Dependencies => Configuration => Backing Services => Build, Release, Run => ...
SERVERLESS:   Codebase => Dependencies => Dev/Prod Parity => Admin Processes
```

---

Either of these seem feasible as an illustration? I'd lean toward the bar chart, personally, but I also have a soft spot for silly-but-also-true infographics.
